apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
spec:
  containers:
    - name: mysql-client
      image: mysql:8.0
      command: ["sleep", "3600"]
      resources:
        requests:
          memory: "250Mi"
          cpu: "250m"
        limits:
          memory: "250Mi"
          cpu: "250m"
