apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ=  # Base64 encoded 'password'
  mysql-user: dXNlcg==              # Base64 encoded 'user'
  mysql-password: cGFzc3dvcmQ=      # Base64 encoded 'password'
