apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer
  selector:
    app: api-pod
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
